LCH-6423: Using prophecy trait. Php unit 10 compatibility.
acquia/contenthub-console pull request #44
Opened 2023-05-11 12:26 UTC by narendradesai

2023-05-12 10:59 UTC, amangrover90 commented on tests/Command/Backups/AcquiaCloudBackupCreateTest.php
> +  use ProphecyTrait;
Better to add this trait in base test class.

2023-05-12 11:00 UTC, amangrover90 requested changes
Left a comment, better to add this trait into another common trait or base classes.

2023-05-15 05:13 UTC, amangrover90 commented on tests/Command/ContentHubHealthCheckWebhookStatusTest.php
> +
Better to add this in ContentHubCommandTestBase than adding in all the inheritors.

2023-05-15 05:14 UTC, amangrover90 requested changes
Left a comment.

2023-05-15 10:45 UTC, saxumVermes approved these changes

2023-05-15 10:48 UTC, merged